name: LIVESTREAM FFMPEG

on:
  workflow_dispatch:
    inputs:
      ffmpegcom:
        description: 'Command ffmpeg'
        required: true

jobs:
  live-streaming:
    runs-on: ubuntu-latest

    steps:
      - name: Run FFmpeg command using Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace jrottenberg/ffmpeg:latest ${{ github.event.inputs.ffmpegcom }}
